// <auto-generated />
using System;
using MaxBundles;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaxBundles.Migrations
{
    [DbContext(typeof(BundleContext))]
    [Migration("20240624173212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaxBundles.Models.Bundle", b =>
                {
                    b.Property<int>("BundleId")
                        .HasColumnType("int");

                    b.HasKey("BundleId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("MaxBundles.Models.BundlePart", b =>
                {
                    b.Property<int>("BundlePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BundlePartId"));

                    b.Property<int>("BundleId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BundlePartId");

                    b.HasIndex("BundleId");

                    b.HasIndex("PartId");

                    b.ToTable("BundleParts");
                });

            modelBuilder.Entity("MaxBundles.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("InventoryCount")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MaxBundles.Models.Bundle", b =>
                {
                    b.HasOne("MaxBundles.Models.Product", "Product")
                        .WithOne()
                        .HasForeignKey("MaxBundles.Models.Bundle", "BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MaxBundles.Models.BundlePart", b =>
                {
                    b.HasOne("MaxBundles.Models.Bundle", "Bundle")
                        .WithMany("BundleParts")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaxBundles.Models.Product", "Part")
                        .WithMany("BundleParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("MaxBundles.Models.Bundle", b =>
                {
                    b.Navigation("BundleParts");
                });

            modelBuilder.Entity("MaxBundles.Models.Product", b =>
                {
                    b.Navigation("BundleParts");
                });
#pragma warning restore 612, 618
        }
    }
}
